-- ===== DROP TABLES =====
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;

-- ===== USER TABLE =====
CREATE TABLE users (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email           VARCHAR(255) NOT NULL UNIQUE,
                       password        VARCHAR(255) NOT NULL
);

-- ===== FILE TABLE =====
CREATE TABLE files (
                       id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id        VARCHAR(255)           NOT NULL UNIQUE,
                       owner_id         BIGINT         NOT NULL,
                       original_name    VARCHAR(255)   NOT NULL,
                       stored_name      VARCHAR(255)   NOT NULL,
                       extension        VARCHAR(10)    NOT NULL,
                       content_type     VARCHAR(100)   NOT NULL,
                       size_bytes       BIGINT         NOT NULL,
                       storage_path     VARCHAR(500)   NOT NULL,
                       sha256_hash      CHAR(64),
                       is_temp          BOOLEAN        NOT NULL DEFAULT FALSE,
                       expires_at       TIMESTAMP,
                       created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       deleted_at       TIMESTAMP,

                       CONSTRAINT fk_files_owner
                           FOREIGN KEY (owner_id) REFERENCES users (id)
                               ON DELETE RESTRICT,

                       CONSTRAINT ck_files_max_size
                           CHECK (size_bytes <= 5 * 1024 * 1024),

                       CONSTRAINT ck_files_allowed_extension
                           CHECK (UPPER(extension) IN ('PNG', 'JPEG', 'JPG', 'DOCX', 'PDF', 'XLSX'))
);

-- INDEXES
CREATE INDEX idx_files_created_at ON files (created_at);
CREATE INDEX idx_files_public_id  ON files (public_id);
CREATE INDEX idx_files_extension  ON files (extension);
CREATE INDEX idx_files_owner      ON files (owner_id);