-- ===== AUTH TABLES =====

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email           VARCHAR(255) NOT NULL UNIQUE,
                       password_hash   VARCHAR(255) NOT NULL,
                       full_name       VARCHAR(255),
                       is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
                       created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
                            user_id     BIGINT NOT NULL,
                            role_id     BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id) REFERENCES users (id)
                                    ON DELETE CASCADE,
                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id) REFERENCES roles (id)
                                    ON DELETE CASCADE
);

-- ===== FILE TABLE =====

DROP TABLE IF EXISTS files;

CREATE TABLE files (
                       id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id        UUID           NOT NULL UNIQUE,          -- UUID exposed in public URLs
                       owner_id         BIGINT         NOT NULL,                 -- FK to users.id
                       original_name    VARCHAR(255)   NOT NULL,                 -- original upload file name
                       stored_name      VARCHAR(255)   NOT NULL,                 -- physical file name (UUID + extension)
                       extension        VARCHAR(10)    NOT NULL,                 -- PNG, PDF, DOCX, ...
                       content_type     VARCHAR(100)   NOT NULL,                 -- MIME type
                       size_bytes       BIGINT         NOT NULL,                 -- file size in bytes
                       storage_path     VARCHAR(500)   NOT NULL,                 -- relative storage path (e.g. 2025/11/20/pdf/R/uuid.pdf)
                       sha256_hash      CHAR(64),                                -- file content hash (SHA-256)
                       is_temp          BOOLEAN        NOT NULL DEFAULT FALSE,   -- temporary file flag
                       expires_at       TIMESTAMP,                               -- optional expiration (TTL)
                       created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       deleted_at       TIMESTAMP,                               -- soft delete marker

                       CONSTRAINT fk_files_owner
                           FOREIGN KEY (owner_id) REFERENCES users (id)
                               ON DELETE RESTRICT,

    -- Max 5 MB
                       CONSTRAINT ck_files_max_size
                           CHECK (size_bytes <= 5 * 1024 * 1024),

    -- Allowed extensions set
                       CONSTRAINT ck_files_allowed_extension
                           CHECK (UPPER(extension) IN ('PNG', 'JPEG', 'JPG', 'DOCX', 'PDF', 'XLSX'))
);

-- INDEXES
CREATE INDEX idx_files_created_at ON files (created_at);
CREATE INDEX idx_files_public_id  ON files (public_id);
CREATE INDEX idx_files_extension  ON files (UPPER(extension));
CREATE INDEX idx_files_owner      ON files (owner_id);
