package com.fileservice.file.pojo.entity;

import com.fileservice.auth.pojo.entity.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity that represents a stored file.
 * <p>
 * This entity maps to the {@code files} table and holds both technical
 * and business-related metadata about the file.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "files")
public class FileEntity {

    /**
     * Internal primary key generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Public UUID used in URLs to reference the file.
     * <p>
     * This value is safe to expose externally and is unique.
     */
    @Column(name = "public_id", nullable = false, unique = true)
    private UUID publicId;

    /**
     * Owner of the file.
     * <p>
     * Non-admin users will typically only see their own files.
     */
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /**
     * Original filename as uploaded by the client.
     */
    @Column(name = "original_name", nullable = false, length = 255)
    private String originalName;

    /**
     * Physical file name used on disk.
     * <p>
     * Usually a UUID plus an extension, decoupled from the original name.
     */
    @Column(name = "stored_name", nullable = false, length = 255)
    private String storedName;

    /**
     * File extension such as {@code PDF}, {@code PNG}, {@code DOCX}.
     */
    @Column(name = "extension", nullable = false, length = 10)
    private String extension;

    /**
     * MIME type of the file, e.g. {@code application/pdf}.
     */
    @Column(name = "content_type", nullable = false, length = 100)
    private String contentType;

    /**
     * Size of the file in bytes.
     * <p>
     * A database-level constraint ensures that the size does not exceed 5 MB.
     */
    @Column(name = "size_bytes", nullable = false)
    private long sizeBytes;

    /**
     * Relative storage path on the file system.
     * <p>
     * Example: {@code 2025/11/23/pdf/R/uuid.pdf}.
     */
    @Column(name = "storage_path", nullable = false, length = 500)
    private String storagePath;

    /**
     * Optional SHA-256 hash of the file content.
     * <p>
     * Can be used for integrity checks or deduplication.
     */
    @Column(name = "sha256_hash", length = 64)
    private String sha256Hash;

    /**
     * Flag that indicates whether this file is temporary.
     * <p>
     * Temporary files may be cleaned up based on {@link #expiresAt}.
     */
    @Column(name = "is_temp", nullable = false)
    private boolean temp = false;

    /**
     * Optional expiration date and time for temporary files.
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    /**
     * Timestamp when the file record was created.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the file record was last updated.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Timestamp when the file was logically deleted.
     * <p>
     * A non-null value indicates a soft delete.
     */
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
